### ISSUE TITLE
Can I use this in full ESRI Javascript API application?

### ISSUE THREAD

**Issue by ghost** [Esri/esri-leaflet-cluster#11]
I know ESRI Javascript API does have a cluster layer js. But I like visual effect of this better. So is it possible? Thanks.

**Comment by jgravois** [comment]
unfortunately no. Leaflet is an entirely separate mapping API so there is no convenient way to port plugins to the ArcGIS API for JavaScript.

That said, since both the code here and [cluster-layer-js](https://github.com/Esri/cluster-layer-js) are open source, you're welcome to dig in deeper yourself to try and incorporate the things you like.

happy to chat more if it'd be helpful.
