### ISSUE TITLE
Query Feature + Marker Cluster

### ISSUE THREAD

**Issue by bhaskarvk** [Esri/esri-leaflet-cluster#15]
If I combine the query example and marker example
https://esri.github.io/esri-leaflet/examples/querying-feature-layers-1.html &
https://esri.github.io/esri-leaflet/examples/clustering-feature-layers.html

The cluster counts don't update correctly when changing the data based on the query.

To see it working , simply combine code appropriately from the two examples, zoom all the way out till you'll see a single cluster with count = 6916. Now change the direction from any to either of the four directions, and then change it back to any. The expected cluster count is 6916, but I see 2000.

**Comment by bhaskarvk** [comment]
Any updates on this ?

**Comment by jgravois** [comment]
i can reproduce the behavior you describe by launching the clustering-feature-layers example with the map zoomed out to level 1. ([live demo](http://jsbin.com/disijid/edit?html,output))

this is occurring because the service is configured to return a maximum of 2000 features for any given query.  

from the [service](https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Trimet_Transit_Stops/FeatureServer/0) metadata: 
> Max Record Count: 2000

when you zoom out far enough, even though Esri Leaflet breaks up the current map extent into a grid and executes more than one query simultaneously, all the features are located within a single cell.

if no local cache from previous queries is present, or if the cache is cleared manually by calling `setWhere()` any feature layer is going to be limited to drawing the features that are retrieved from the service itself.

**Comment by bhaskarvk** [comment]
Thanks for the update, perhaps a note in the documentation would be helpful.

**Comment by jgravois** [comment]
> perhaps a note in the documentation would be helpful.

agreed.
