### ISSUE TITLE
Gruntfile.js not found

### ISSUE THREAD

**Issue by lmorroni** [Esri/esri-leaflet-cluster#16]
The directions say to use grunt to run this demo but there is no Gruntfile in the master branch.  I saw one in the 1.0 tagged release but that did not work for me.  Am I missing something?
Thank You,
Larry

**Comment by jgravois** [comment]
in #4 i refactored the build process to mimic how things are handled in esri-leaflet and forgot to update the README. instead of making a call to grunt, [`npm start`](https://github.com/Esri/esri-leaflet-cluster/blob/180895fa8766570c246f80dd00e1008e28a41e1c/package.json#L70) is now used to trigger a rollup build and recompile when changes to the raw source are detected.

this means that the development instructions need to be edited to follow the same pattern as [esri-leaflet](https://github.com/esri/esri-leaflet#development-instructions) (and our other plugins), if you're able to make a pull request to update the documentation, it'd be *sincerely* appreciated.  if not, i will find time myself sometime soon.

**Comment by jgravois** [comment]
fixed in 29925d7d4ab57661af6135c33269258c5994ca21. don't be shy if you have any other questions.
